title: "Model Context Protocol"
description: "Documentation for the Model Context Protocol (MCP)"
baseurl: "/mcp-documentation"
url: "https://jmanhype.github.io"

theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.5.3

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

search_enabled: true
heading_anchors: true

color_scheme: light

aux_links:
  "MCP on GitHub":
    - "https://github.com/jmanhype/mcp-documentation"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/jmanhype/mcp-documentation"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"